const BACKEND_URL = "https://mindmotion-site-production.up.railway.app";

document.addEventListener('DOMContentLoaded', () => {
    const generateBtn = document.querySelector('#generate-btn');
    const statusText = document.querySelector('#status-display');
    const scriptInput = document.querySelector('#script-input');
    const progressBar = document.querySelector('#progress-bar');
    const progressContainer = document.querySelector('#progress-container');
    const previewBox = document.getElementById('video-preview-box');
    const previewPlayer = document.getElementById('preview-player');
    const shareHub = document.getElementById('share-hub');

    // 1. THE CONSOLE LOGIC
    function updateConsole(msg) {
        const consoleBox = document.querySelector('#engine-console');
        if (consoleBox) {
            const time = new Date().toLocaleTimeString([], { hour12: false });
            consoleBox.innerHTML += `> [${time}] ${msg}<br>`;
            consoleBox.scrollTop = consoleBox.scrollHeight;
        }
    }

    // 2. THE MAIN ACTION FUNCTION
    async function startEngineFlow() {
        const script = scriptInput.value;
        const format = document.querySelector('#format-selector').value;

        if (!script) {
            alert("Asif, please enter your Psychology notes first!");
            return;
        }

        // UI Reset
        statusText.innerText = "🚀 Connecting to Swarm...";
        updateConsole("System Override: Manual Start Initiated.");
        if (previewBox) previewBox.style.display = "none"; 
        if (shareHub) shareHub.style.display = "none";
        
        generateBtn.disabled = true;
        progressContainer.style.display = "block";
        progressBar.style.width = "5%";

        try {
            const response = await fetch(`${BACKEND_URL}/generate`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ script, format })
            });

            const data = await response.json();
            
            if (data.job_id) {
                updateConsole(`Job ID Created: ${data.job_id}`);
                pollStatus(data.job_id);
            }
        } catch (error) {
            statusText.innerText = "❌ Connection Error!";
            updateConsole("ERROR: Failed to reach the Swarm engine.");
            generateBtn.disabled = false;
        }
    }

    if (generateBtn) {
        generateBtn.onclick = startEngineFlow;
    }

    // 3. STATUS POLLING
    async function pollStatus(jobId) {
        let progress = 10;
        let lastStatus = "";

        const interval = setInterval(async () => {
            try {
                const res = await fetch(`${BACKEND_URL}/status/${jobId}`);
                const data = await res.json();

                if (data.status !== lastStatus) {
                    updateConsole(`System Update: ${data.status}`);
                    lastStatus = data.status;
                }

                if (data.status.includes("Slicing")) progress = 25;
                else if (data.status.includes("Rendering")) progress = 65;
                else if (data.status.includes("Stitching")) progress = 90;
                else if (data.status === "Completed") {
                    progress = 100;
                    clearInterval(interval);
                    
                    // Show Preview
                    if (previewBox && previewPlayer) {
                        previewBox.style.display = "block";
                        previewPlayer.src = `${BACKEND_URL}/download/${jobId}`;
                        previewPlayer.load();
                        updateConsole("Visual Preview Generated.");
                    }

                    // Activate Share Hub
                    if (shareHub) {
                        const whatsappBtn = document.getElementById('share-whatsapp');
                        const twitterBtn = document.getElementById('share-twitter');
                        const videoUrl = `${BACKEND_URL}/download/${jobId}`;
                        const shareMsg = encodeURIComponent("Check out my MA Psychology video generated by MindMotion AI! 🧠");
                        
                        whatsappBtn.href = `https://api.whatsapp.com/send?text=${shareMsg}%20${videoUrl}`;
                        twitterBtn.href = `https://twitter.com/intent/tweet?text=${shareMsg}&url=${videoUrl}`;
                        
                        shareHub.style.display = "block";
                    }

                    statusText.innerHTML = `
                        <div style="color: #008080; font-weight: bold; margin-top: 10px;">
                            ✅ Video Ready! <br>
                            <a href="${BACKEND_URL}/download/${jobId}" class="download-btn" target="_blank" style="display:inline-block; margin-top:10px; background:#008080; color:white; padding:10px 20px; text-decoration:none; border-radius:5px;">
                                📥 Download Branded Video
                            </a>
                        </div>
                    `;
                    updateConsole("SUCCESS: Social Share Hub activated.");
                    generateBtn.disabled = false;
                }

                progressBar.style.width = progress + "%";
                if (data.status !== "Completed") {
                    statusText.innerText = "📊 " + data.status;
                }

            } catch (err) {
                console.log("Checking status...");
            }
        }, 2000); 
    }
});
